# port config
server:
  port: 8000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: food-app

  # db config
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    # hikari config
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  # jpa and hibernate config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    naming:
      strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# logging
logging:
  level:
    root: INFO

# security config
application:
  security:
    jwt:
      header: Authorization
      secretKey: 79cc7b97590093a0b8d187a8a724e39a385d6fe051a5fcdf14e1ff642e48e6eb
      expiration: 86400000
    cors:
      allowed-origins:
        - http://localhost:5173
